services:
  bazzar-app:
    container_name: bazzar-app
    image: danielschatz/bazzar-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
